name: Deploy project
on: push
jobs:
  run_unit_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS version
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  deploy:
    runs-on: ubuntu-22.04
    needs: [run_unit_tests]
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS version
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ..."